feat: Add game clear reward gem
HY-CtrlS/Invaders-SDP pull request #21
Opened 2024-10-14 16:56 UTC by Koominjae

## Add function to give 1 gem when player clears game
1 gem is given every time each game is cleared. ('Clear' means when you complete without dying at the last level)

## Changes
`ScoreScreen.java`
   - Add `saveGem()` for increasing 1 gem
   - Add conditions to draw game clear screen and load `saveGem()` only when game is cleared

`DrawManager.java`
   - Add `drawGameClear()` to draw game clear screen

![clear screen (소형)](https://github.com/user-attachments/assets/31858e40-c15a-419c-9284-57369cd8e319)
![log](https://github.com/user-attachments/assets/1afc3633-5c2f-482b-9279-37546cfa6ff0)
![clear gem (소형)](https://github.com/user-attachments/assets/d48c0d30-18e4-4689-82df-f255c7c416d1)

2024-10-14 17:20 UTC, suhynnoh commented on src/engine/DrawManager.java
> +		String gameClearString = "Game Clear";
`drawGameClear` 메소드와 `drawGameOver` 메소드가 이 한 줄을 제외하곤 전부 동일한 것 같습니다.

기존 `drawGameOver` 메소드의 이름을 `drawGameEnd` 로 변경하고, `isGameClear` 라는 불리언 변수를 입력 받아 `gameEndString` 을 분기하는 건 어떨까요?

```suggestion
		String gameEndString = isGameClear ? "Game Clear" : "Game Over";
```

2024-10-14 17:20 UTC, suhynnoh commented on src/screen/ScoreScreen.java
> +		} // CtrlS
this.isGameClear 필드를 추가해, ScoreScreen 생성자에서 작성해주신 조건문을 활용해 isGameClear를 초기화 할 수 있을 것 같습니다.

수정된 drawGameEnd는 다음과 같이 isGameClear 필드를 추가해서 호출합니다.
```suggestion
		drawManager.drawGameEnd(this, this.inputDelay.checkFinished(), this.isNewRecord, this.isGameClear); // CtrlS
```

2024-10-14 17:24 UTC, Koominjae commented on src/screen/ScoreScreen.java
> +		} // CtrlS
불필요한 코드 라인 수 증가도 피하고 좋은 거 같습니다. 반영해보도록 하겠습니다.

2024-10-15 02:18 UTC, suhynnoh approved these changes
빠른 반영 감사합니다. `saveGem` 호출하는 부분도 `isGameClear` 로 바꿀 수 있는 것은 생각 못했는데, 이 부분도 좋은 것 같네요. 승인했습니다!

2024-10-15 03:45 UTC, Geguuuul requested changes
log 출력 부분에 You eared를 You earned로만 고쳐주시면 될 것 같습니다.

2024-10-15 03:45 UTC, Geguuuul commented on src/screen/ScoreScreen.java
> +			logger.info("You eared 1 Gem for Game Clear");
You earned에서 n에 빠져 있습니다.

2024-10-15 03:49 UTC, Geguuuul requested changes
You eared에서 You earned로 고치면 될 것 같습니다. 이외에는 괜찮은 것 같습니다.

2024-10-15 03:49 UTC, Geguuuul commented on src/screen/ScoreScreen.java
> +			logger.info("You eared 1 Gem for Game Clear");
```suggestion
			logger.info("You earned 1 Gem for Game Clear");
```

2024-10-15 04:00 UTC, Geguuuul approved these changes

2024-10-15 04:01 UTC, Koominjae commented on src/screen/ScoreScreen.java
> +			logger.info("You eared 1 Gem for Game Clear");
수정했습니다

2024-10-15 04:02 UTC, merged